name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


repos:
- repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
- repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8

    
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.7", "pypy-3.8", "pypy-3.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Run Tests
      run: python test/test_addition_package.py

    - name: Build & Push Image
      run: |
        echo "${{ secrets.DockerPW }}" | docker login -u "maiallam57" --password-stdin
        docker image build -t maiallam57/my_actions:latest .
        docker push maiallam57/my_actions:latest
